-- Caregiver <-> Child linkage for Lumin
-- Run in Supabase SQL editor.

create table if not exists public.caregiver_codes (
  code text primary key,
  caregiver_id uuid not null references auth.users(id) on delete cascade,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.caregiver_patients (
  id bigint generated by default as identity primary key,
  caregiver_id uuid not null references auth.users(id) on delete cascade,
  child_id uuid not null references auth.users(id) on delete cascade,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (caregiver_id, child_id)
);

alter table public.sessions add column if not exists child_id uuid references auth.users(id) on delete set null;
alter table public.emotion_logs add column if not exists child_id uuid references auth.users(id) on delete set null;
alter table public.activities add column if not exists child_id uuid references auth.users(id) on delete set null;
alter table public.alerts add column if not exists child_id uuid references auth.users(id) on delete set null;

create index if not exists idx_sessions_child_id on public.sessions(child_id);
create index if not exists idx_emotion_logs_child_id on public.emotion_logs(child_id);
create index if not exists idx_activities_child_id on public.activities(child_id);
create index if not exists idx_alerts_child_id on public.alerts(child_id);
create index if not exists idx_caregiver_patients_caregiver on public.caregiver_patients(caregiver_id);
create index if not exists idx_caregiver_patients_child on public.caregiver_patients(child_id);

alter table public.caregiver_codes enable row level security;
alter table public.caregiver_patients enable row level security;

-- A caregiver can manage and read only their own codes.
drop policy if exists caregiver_codes_select_own on public.caregiver_codes;
create policy caregiver_codes_select_own
  on public.caregiver_codes
  for select
  using (caregiver_id = auth.uid());

drop policy if exists caregiver_codes_manage_own on public.caregiver_codes;
create policy caregiver_codes_manage_own
  on public.caregiver_codes
  for all
  using (caregiver_id = auth.uid())
  with check (caregiver_id = auth.uid());

-- Caregiver can read only their assigned children.
drop policy if exists caregiver_patients_select_own on public.caregiver_patients;
create policy caregiver_patients_select_own
  on public.caregiver_patients
  for select
  using (caregiver_id = auth.uid());

-- Child account can read their own linkage row.
drop policy if exists caregiver_patients_select_child on public.caregiver_patients;
create policy caregiver_patients_select_child
  on public.caregiver_patients
  for select
  using (child_id = auth.uid());

-- Child signup flow can create linkage rows only for itself.
drop policy if exists caregiver_patients_insert_child_self on public.caregiver_patients;
create policy caregiver_patients_insert_child_self
  on public.caregiver_patients
  for insert
  with check (child_id = auth.uid());

-- Caregiver can update their own linkage rows.
drop policy if exists caregiver_patients_update_own on public.caregiver_patients;
create policy caregiver_patients_update_own
  on public.caregiver_patients
  for update
  using (caregiver_id = auth.uid())
  with check (caregiver_id = auth.uid());

-- OPTIONAL: tighten existing tables with child-aware RLS policies.
-- Replace or merge with your current project policies before running in production.
